### PR TITLE
Issue #2450: Refactor output and error handling

### PR DESCRIPTION
**Pull request by kostajh**
@dmurphy1 This PR makes the following changes:

- Updates our composer packages to latest stable versions
- Uses Symfony style package for output
- Simplifies the time entry retrieval process to a single step. Before we gathered project level data for all projects, then went through each one and retrieved time entries for each project -- now this is done in one pass.
- Adds clickable URLs to time entry records both in Slack output and in Sumac console output, so it's easy to jump to a record to correct it
- Use progress bar indicators for the two operations (retrieving time entries, and processing them). The progress bar will look decent on Jenkins too.
- Dump all information about records processed at the end of the sync, and format it in a table with the minimum information needed to be useful and actionable.
- Reword some of the messages, and light refactoring throughout

### CODE REVIEW

**Comment by dmurphy1** [comment]
Hi @kostajh - when testing locally, I entered a test time entry in Havrest for tomorrow for `.3` hours to Tech Infrastructure / Code Review with description `#2486: Testing`. I then ran:

`docker run --net redmine_default -it --rm -v $(pwd):/usr/src/sumac savaslabs/sumac:dev sync -u 20170222:20170223`

And I got the following error output:
```
Sumac time sync from  20170222 to 20170223
==========================================

Getting time entries data for 28 Redmine projects
-------------------------------------------------

 28/28 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

                                                                                                                        
 [WARNING] Skipped projects Internal, in config.yml excludes list                                                       
                                                                                                                        

 ! [NOTE] Found 1 entries with possible Redmine IDs out of 1 total                                                      

Processing entries
------------------

 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ! [NOTE] Notified  of time entry errors via Slack.                                                                     

Successes
---------


Fatal error: Uncaught TypeError: Argument 2 passed to Symfony\Component\Console\Style\SymfonyStyle::table() must be of the type array, null given, called in /usr/src/sumac/src/Sumac/Console/Command/SyncCommand.php on line 936 and defined in /usr/src/sumac/vendor/symfony/console/Style/SymfonyStyle.php:185
Stack trace:
#0 /usr/src/sumac/src/Sumac/Console/Command/SyncCommand.php(936): Symfony\Component\Console\Style\SymfonyStyle->table(Array, NULL)
#1 /usr/src/sumac/src/Sumac/Console/Command/SyncCommand.php(905): Sumac\Console\Command\SyncCommand->renderEntries('Successes', Array, NULL)
#2 /usr/src/sumac/vendor/symfony/console/Command/Command.php(256): Sumac\Console\Command\SyncCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /usr/src/sumac/vendor/symfony/console/Application.php(820): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /usr/src/ in /usr/src/sumac/vendor/symfony/console/Style/SymfonyStyle.php on line 185
```

**Comment by dmurphy1** [comment]
Hi @kostajh - I pushed up an update to the README, and also an indentation fix for coding standards.

If I run the sync and no time entries are found, I still get that error (see below), I'm not sure if that will ever happen in practice though. Otherwise this is working great and is so much more usable 👍 !!

```
 ! [NOTE] Found 0 entries with possible Redmine IDs out of 0 total                                                      

Processing entries
------------------

    0 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]

 ! [NOTE] Notified  of time entry errors via Slack.                                                                     


Fatal error: Uncaught TypeError: Argument 2 passed to Symfony\Component\Console\Style\SymfonyStyle::table() must be of the type array, null given, called in /usr/src/sumac/src/Sumac/Console/Command/SyncCommand.php on line 926 and defined in /usr/src/sumac/vendor/symfony/console/Style/SymfonyStyle.php:185
Stack trace:
#0 /usr/src/sumac/src/Sumac/Console/Command/SyncCommand.php(926): Symfony\Component\Console\Style\SymfonyStyle->table(Array, NULL)
#1 /usr/src/sumac/vendor/symfony/console/Command/Command.php(256): Sumac\Console\Command\SyncCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /usr/src/sumac/vendor/symfony/console/Application.php(820): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /usr/src/sumac/vendor/symfony/console/Application.php(187): Symfony\Component\Console\Application->doRunCommand(Object(Sumac\Console\Command\SyncComma in /usr/src/sumac/vendor/symfony/console/Style/SymfonyStyle.php on line 185
```

**Comment by dmurphy1** [comment]
Hi @kostajh - I tested locally with the full set of data, following your instructions in the Redmine issue, first without the `--update` flag, then with it and got `644 errors and 5625 successes occurred during sync` both times. So I think this is good to go! Great work, the UI is really nice :1st_place_medal: ⭐️ 👍 !

FYI: Chris and I also pushed some minor tweaks to the README.

**Comment by kostajh** [comment]
Cool! Let's do it!

**Pull request merged**
